version: '3'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile.node
    volumes:
      - .:/usr/src/app
      - /recordings:/usr/src/app/recordings
    ports:
      - 30817:3000
    command: npm start
    environment:
      - NODE_ENV=$NODE_ENV
    restart: unless-stopped
    depends_on:
      - db
    networks:
      - app-network

  db:
    image: mongo:latest
    ports:
      - 27017:27017
    restart: always
    volumes:
      - db:/data/db
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  db: {}
