# Use jrottenberg/ffmpeg image as the base
FROM jrottenberg/ffmpeg:4.4-ubuntu

# Set the working directory
WORKDIR /app

# Copy files from the local 'app' directory to the '/app' directory in the container
COPY ./app /app

# Set the default command to execute
CMD ["/bin/bash"]
