# base image
FROM node:alpine

# Create app directory
WORKDIR /usr/src/app

# Install app dependencies
COPY package*.json .

# Install ffmpeg and npm dependencies
RUN apk add --no-cache ffmpeg && \
    npm ci

# Bundle app source
COPY . .

EXPOSE 3000
CMD [ "npm", "start" ]
